export const urunler = [
  {
    id: 1,
    name: 'In the Blacks',
    category: 'Outfit',
    brand: 'Zara',
    price: 75.99,
    image: 'images/insta-item1.jpg',
    size: ['S', 'M', 'L', 'XL'],
    material: 'Cotton',
    comments: [
      {
        commenter_id: 1001,
        commenter_username: 'outdoorfan',
        commenter_type: 'User',
        commenter_comment: 'Ateşin üzerinde bile kullanabiliyorum!',
      },
      {
        commenter_id: 1031,
        commenter_username: 'kampkocu',
        commenter_type: 'User',
        commenter_comment: 'Isıyı güzel tutuyor.',
      },
      {
        commenter_id: 1032,
        commenter_username: 'kahvecican',
        commenter_type: 'User',
        commenter_comment: 'Sabah kahvelerim için birebir.',
      },
    ],
  },
  {
    id: 2,
    name: 'The Beauty of Pink',
    category: 'Outfit',
    brand: 'HomeMax',
    price: 150.25,
    image: '../images/insta-item3.jpg',
    size: ['S', 'M', 'XL'],
    material: 'Cotton',
    comments: [
      {
        commenter_id: 1002,
        commenter_username: 'duzenlihayat',
        commenter_type: 'User',
        commenter_comment: 'Tüm makyaj malzemelerimi topladı!',
      },
      {
        commenter_id: 1033,
        commenter_username: 'ofistasarim',
        commenter_type: 'User',
        commenter_comment: 'Çekmece karışıklığına son.',
      },
      {
        commenter_id: 1034,
        commenter_username: 'minimalistanne',
        commenter_type: 'User',
        commenter_comment: 'Kullanımı çok pratik.',
      },
    ],
  },
  {
    id: 3,
    name: 'Madonna Yaka Gömlek',
    category: 'Clothing',
    brand: 'NeoForm',
    price: 57.1,
    image: '../images/insta-item5.jpg',
    size: ['L', 'XL'],
    material: 'Cotton',
    comments: [
      {
        commenter_id: 1003,
        commenter_username: 'stilsahibi',
        commenter_type: 'User',
        commenter_comment: 'Şık ve dayanıklı, tavsiye ederim.',
      },
      {
        commenter_id: 1035,
        commenter_username: 'aksesuarmeraklisi',
        commenter_type: 'User',
        commenter_comment: 'Çantamda az yer kaplıyor.',
      },
      {
        commenter_id: 1036,
        commenter_username: 'gozluksever',
        commenter_type: 'User',
        commenter_comment: 'Gözlükleri çok iyi koruyor.',
      },
    ],
  },
  {
    id: 4,
    name: 'Green Jacket',
    category: 'Clothing',
    brand: 'DS Clothing',
    price: 135.75,
    image: '../images/insta-item6.jpg',
    size: ['S', 'M', 'L'],
    comments: [
      {
        commenter_id: 1004,
        commenter_username: 'hayattakalan',
        commenter_type: 'User',
        commenter_comment: 'Kampta hayat kurtardı!',
      },
      {
        commenter_id: 1037,
        commenter_username: 'elaletisever',
        commenter_type: 'User',
        commenter_comment: 'Her fonksiyonu işe yarıyor.',
      },
      {
        commenter_id: 1038,
        commenter_username: 'dogakoc',
        commenter_type: 'User',
        commenter_comment: 'Boyutuna göre çok işlevsel.',
      },
    ],
  },
  {
    id: 5,
    name: 'Eric Wick Limited Edition : The Black',
    category: 'Clothing',
    brand: 'EW',
    price: 252.35,
    image: '../images/post-image2.jpg',
    size: ['M', 'L', 'XL'],
    material: 'Cotton',
    comments: [
      {
        commenter_id: 1005,
        commenter_username: 'ayakkabisever',
        commenter_type: 'User',
        commenter_comment: 'Yerden tasarruf sağladı.',
      },
      {
        commenter_id: 1039,
        commenter_username: 'evduzenleyici',
        commenter_type: 'User',
        commenter_comment: 'Kurulumu kolay.',
      },
      {
        commenter_id: 1040,
        commenter_username: 'minimalistadam',
        commenter_type: 'User',
        commenter_comment: 'Balkona bile koyabiliyorum.',
      },
    ],
  },
  {
    id: 6,
    name: 'Creamy Sweatshirt',
    category: 'Clothing',
    brand: 'CampLite',
    price: 109.8,
    image: '../images/post-image4.jpg',
    size: ['M', 'L'],
    material: 'Cotton',
    comments: [
      {
        commenter_id: 1006,
        commenter_username: 'gececi',
        commenter_type: 'User',
        commenter_comment: 'Gece kampı için birebir.',
      },
      {
        commenter_id: 1041,
        commenter_username: 'isiklisever',
        commenter_type: 'User',
        commenter_comment: 'Işığı güçlü ve uzun ömürlü.',
      },
      {
        commenter_id: 1042,
        commenter_username: 'kampgezer',
        commenter_type: 'User',
        commenter_comment: 'Askıya asılması çok pratik.',
      },
    ],
  },
  {
    id: 7,
    name: 'Sunglasses',
    category: 'Accessories',
    brand: 'DeskCraft',
    price: 18.45,
    image: '../images/post-image6.jpg',
    material: 'Plastic',
    comments: [
      {
        commenter_id: 1007,
        commenter_username: 'ofissever',
        commenter_type: 'User',
        commenter_comment: 'Masa üstüm çok düzenli oldu.',
      },
      {
        commenter_id: 1043,
        commenter_username: 'sanatkar',
        commenter_type: 'User',
        commenter_comment: 'Ahşap kalitesi çok iyi.',
      },
      {
        commenter_id: 1044,
        commenter_username: 'duzenbagimlisi',
        commenter_type: 'User',
        commenter_comment: 'Kalemlerim hep bir yerde artık.',
      },
    ],
  },
  {
    id: 8,
    name: 'Sleeveless Linen Dress',
    category: 'Clothing',
    brand: 'Zara',
    price: 64.62,
    image: '../images/post-image7.jpg',
    size: ['S', 'M', 'L'],
    material: 'Linen',
    comments: [
      {
        commenter_id: 1008,
        commenter_username: 'pratikev',
        commenter_type: 'User',
        commenter_comment: 'Havlular için ideal.',
      },
      {
        commenter_id: 1045,
        commenter_username: 'askisever',
        commenter_type: 'User',
        commenter_comment: 'Montlarımı artık yere atmıyorum.',
      },
      {
        commenter_id: 1046,
        commenter_username: 'evkurucu',
        commenter_type: 'User',
        commenter_comment: 'Görünümü sade ve şık.',
      },
    ],
  },
  {
    id: 9,
    name: 'Detail of Greens',
    category: 'Outfit',
    brand: 'Zara',
    price: 340.0,
    image: '../images/product-item-1.jpg',
    size: ['M', 'L'],
    comments: [
      {
        commenter_id: 1008,
        commenter_username: 'pratikev',
        commenter_type: 'User',
        commenter_comment: 'Havlular için ideal.',
      },
      {
        commenter_id: 1045,
        commenter_username: 'askisever',
        commenter_type: 'User',
        commenter_comment: 'Montlarımı artık yere atmıyorum.',
      },
      {
        commenter_id: 1046,
        commenter_username: 'evkurucu',
        commenter_type: 'User',
        commenter_comment: 'Görünümü sade ve şık.',
      },
    ],
  },
  {
    id: 10,
    name: 'Crop Top',
    category: 'Clothing',
    brand: 'Nike',
    price: 91.25,
    image: '../images/product-item-3.jpg',
    size: ['S', 'M', 'L', 'XL'],
    comments: [
      {
        commenter_id: 1008,
        commenter_username: 'pratikev',
        commenter_type: 'User',
        commenter_comment: 'Havlular için ideal.',
      },
      {
        commenter_id: 1045,
        commenter_username: 'askisever',
        commenter_type: 'User',
        commenter_comment: 'Montlarımı artık yere atmıyorum.',
      },
      {
        commenter_id: 1046,
        commenter_username: 'evkurucu',
        commenter_type: 'User',
        commenter_comment: 'Görünümü sade ve şık.',
      },
    ],
  },
  {
    id: 11,
    name: 'Dress with Flovers',
    category: 'Clothing',
    brand: 'B&O',
    price: 110.5,
    image: '../images/product-item-5.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    comments: [
      {
        commenter_id: 1008,
        commenter_username: 'pratikev',
        commenter_type: 'User',
        commenter_comment: 'Havlular için ideal.',
      },
      {
        commenter_id: 1045,
        commenter_username: 'askisever',
        commenter_type: 'User',
        commenter_comment: 'Montlarımı artık yere atmıyorum.',
      },
      {
        commenter_id: 1046,
        commenter_username: 'evkurucu',
        commenter_type: 'User',
        commenter_comment: 'Görünümü sade ve şık.',
      },
    ],
  },
  {
    id: 12,
    name: 'Like a Mother',
    category: 'Outfit',
    brand: 'B&O',
    price: 200.5,
    image: '../images/product-item-6.jpg',
    size: ['L', 'XL'],
    comments: [
      {
        commenter_id: 1008,
        commenter_username: 'pratikev',
        commenter_type: 'User',
        commenter_comment: 'Havlular için ideal.',
      },
      {
        commenter_id: 1045,
        commenter_username: 'askisever',
        commenter_type: 'User',
        commenter_comment: 'Montlarımı artık yere atmıyorum.',
      },
      {
        commenter_id: 1046,
        commenter_username: 'evkurucu',
        commenter_type: 'User',
        commenter_comment: 'Görünümü sade ve şık.',
      },
    ],
  },
  {
    id: 13,
    name: 'White Shirt',
    category: 'Clothing',
    brand: 'Mavi',
    price: 180.0,
    image: '../images/product-item-8.jpg',
    size: ['S', 'M', 'L'],
    comments: [
      {
        commenter_id: 1008,
        commenter_username: 'pratikev',
        commenter_type: 'User',
        commenter_comment: 'Havlular için ideal.',
      },
      {
        commenter_id: 1045,
        commenter_username: 'askisever',
        commenter_type: 'User',
        commenter_comment: 'Montlarımı artık yere atmıyorum.',
      },
      {
        commenter_id: 1046,
        commenter_username: 'evkurucu',
        commenter_type: 'User',
        commenter_comment: 'Görünümü sade ve şık.',
      },
    ],
  },
  {
    id: 14,
    name: 'Green Sweater',
    category: 'Clothing',
    brand: 'Yakamoz',
    price: 156.0,
    image: '../images/product-item-10.jpg',
    size: ['M', 'L', 'XL'],
    comments: [
      {
        commenter_id: 1008,
        commenter_username: 'pratikev',
        commenter_type: 'User',
        commenter_comment: 'Havlular için ideal.',
      },
      {
        commenter_id: 1045,
        commenter_username: 'askisever',
        commenter_type: 'User',
        commenter_comment: 'Montlarımı artık yere atmıyorum.',
      },
      {
        commenter_id: 1046,
        commenter_username: 'evkurucu',
        commenter_type: 'User',
        commenter_comment: 'Görünümü sade ve şık.',
      },
    ],
  },
];
